apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: csvserver_records
      static_configs:
      - targets: ['csvserver:80']
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-cm
